# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Xcaffold < Formula
  desc "Deterministic agent configuration compiler for AI coding platforms. Compile .xcaf blueprints into native agent configurations."
  homepage "https://github.com/saero-ai/xcaffold"
  version "0.12.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/saero-ai/xcaffold/releases/download/v0.12.0/xcaffold_darwin_amd64.tar.gz"
      sha256 "259b6dc9f24545f877d8152dac79f60662401170fd4b58d9823790b23e152c1a"

      define_method(:install) do
        bin.install "xcaffold"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/saero-ai/xcaffold/releases/download/v0.12.0/xcaffold_darwin_arm64.tar.gz"
      sha256 "20322544007a8699e1c91e9836b2ae28f833cad7946b2040f862e1f63c2aa76c"

      define_method(:install) do
        bin.install "xcaffold"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/saero-ai/xcaffold/releases/download/v0.12.0/xcaffold_linux_amd64.tar.gz"
      sha256 "266f166f447c2b248973f99b53fb6ed9fea26ed1b80363fcb2e654757222c687"
      define_method(:install) do
        bin.install "xcaffold"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/saero-ai/xcaffold/releases/download/v0.12.0/xcaffold_linux_arm64.tar.gz"
      sha256 "e33d8ec1b44d2caaa85ee1c0c7b09d62e7133f5d94287ab7b6a42006816fc080"
      define_method(:install) do
        bin.install "xcaffold"
      end
    end
  end

  test do
    system "#{bin}/xcaffold", "--version"
  end
end
