# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Xcaffold < Formula
  desc "Deterministic agent configuration compiler for AI coding platforms. Compile .xcaf blueprints into native agent configurations."
  homepage "https://github.com/saero-ai/xcaffold"
  version "0.8.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/saero-ai/xcaffold/releases/download/v0.8.0/xcaffold_darwin_amd64.tar.gz"
      sha256 "6bceb0d59705ef026c10a3991324d216e73362a9ad9215b12954628f5f7cc8f4"

      define_method(:install) do
        bin.install "xcaffold"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/saero-ai/xcaffold/releases/download/v0.8.0/xcaffold_darwin_arm64.tar.gz"
      sha256 "bbfd8c65a06135efcf783247b37ba09a9e65bdd0ed97a9a1aa976986c77894a5"

      define_method(:install) do
        bin.install "xcaffold"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/saero-ai/xcaffold/releases/download/v0.8.0/xcaffold_linux_amd64.tar.gz"
      sha256 "6331ff0b4403bf68cce3242984836d113410a733aad612c193d11a77adb82399"
      define_method(:install) do
        bin.install "xcaffold"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/saero-ai/xcaffold/releases/download/v0.8.0/xcaffold_linux_arm64.tar.gz"
      sha256 "3e12053897f493becf482f0352e4990e67f6e9a9470939e6772284d7b1ab01e8"
      define_method(:install) do
        bin.install "xcaffold"
      end
    end
  end

  test do
    system "#{bin}/xcaffold", "--version"
  end
end
